/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formulario;

import clases.Credencial;

/**
 *
 * @author Miguel
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private Credencial credencial;
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal(Credencial credencial) 
    {
        initComponents();
        dpPrincipal.setSize(1000, 800);
        this.credencial = credencial;
        lblNombreUsuario.setText("Usuario: " + credencial.getUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpPrincipal = new javax.swing.JDesktopPane();
        lblNombreUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnSalir = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        mnProducto = new javax.swing.JMenuItem();
        mnKardex = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        mnProductoEditar = new javax.swing.JMenuItem();
        mnClienteEditar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dpPrincipal.setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().add(dpPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 400));

        lblNombreUsuario.setText("Usuario: ....");
        getContentPane().add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 150, -1));

        jMenu1.setText("Archivo");

        mnSalir.setText("Salir");
        mnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnSalir);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Nuevo");

        jMenu5.setText("Inventario");

        mnProducto.setText("Producto");
        mnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnProductoActionPerformed(evt);
            }
        });
        jMenu5.add(mnProducto);

        mnKardex.setText("Kardex");
        mnKardex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKardexActionPerformed(evt);
            }
        });
        jMenu5.add(mnKardex);

        jMenu4.add(jMenu5);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Editar");

        jMenu6.setText("Invetario");

        mnProductoEditar.setText("Producto");
        mnProductoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnProductoEditarActionPerformed(evt);
            }
        });
        jMenu6.add(mnProductoEditar);

        mnClienteEditar.setText("Cliente");
        mnClienteEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnClienteEditarActionPerformed(evt);
            }
        });
        jMenu6.add(mnClienteEditar);

        jMenu3.add(jMenu6);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Ayuda");

        mnAcercaDe.setText("Acerca de");
        mnAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAcercaDeActionPerformed(evt);
            }
        });
        jMenu2.add(mnAcercaDe);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnSalirActionPerformed

    private void mnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnProductoActionPerformed
        // TODO add your handling code here:
        FrmInternalProducto frm = new FrmInternalProducto();
        dpPrincipal.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_mnProductoActionPerformed

    private void mnKardexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKardexActionPerformed
        // TODO add your handling code here:
        FrmInternalKardex frm = new FrmInternalKardex();
        dpPrincipal.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_mnKardexActionPerformed

    private void mnProductoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnProductoEditarActionPerformed
        // TODO add your handling code here:
        FrmInternalEditarProducto frm = new FrmInternalEditarProducto();
        dpPrincipal.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_mnProductoEditarActionPerformed

    private void mnClienteEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnClienteEditarActionPerformed
        // TODO add your handling code here:
        FrmInternalCliente frm = new FrmInternalCliente();
        dpPrincipal.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_mnClienteEditarActionPerformed

    private void mnAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAcercaDeActionPerformed
        // TODO add your handling code here:
        FrmInternalAcercaDe frm = new FrmInternalAcercaDe();
        dpPrincipal.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_mnAcercaDeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpPrincipal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JMenuItem mnAcercaDe;
    private javax.swing.JMenuItem mnClienteEditar;
    private javax.swing.JMenuItem mnKardex;
    private javax.swing.JMenuItem mnProducto;
    private javax.swing.JMenuItem mnProductoEditar;
    private javax.swing.JMenuItem mnSalir;
    // End of variables declaration//GEN-END:variables
}
